name: "Fortify Security Check"
description: "Scan source code in repository with self-hosted Fortify SAST"
inputs:
  fortify-ssc-url:
    description: "Fortify SSC URL"
    required: true
  fortify-sc-sast-url:
    description: "Fortify SC SAST URL"
    required: true
  ssc-token:
    description: "Fortify SSC token"
    required: true
  ssc-sast-token:
    description: "Fortify SSC SAST shared token"
    required: true
  application:
    description: "Application name in Fortify SSC"
    required: true
  application-version:
    description: "Application version in Fortify SSC"
    required: true
  base-version:
    description: "Base version for copying state when creating PR versions"
    required: false
    default: "master"
  sast-version:
    description: "Fortify SSC SAST module version"
    required: false
    default: "23.2"
  github-token:
    description: "GitHub token"
    required: false
  exit-with-error-on-severity:
    description: "Fail the GitHub Workflow if issues with the specified and above severity are detected during the scan"
    required: false
    default: "Medium"
  enable-report-comment:
    description: "Add comment with summary to pull request conversation"
    required: false
    default: "true"
outputs:
  total-issues:
    description: "Total number of issues found"
    value: ${{ steps.report.outputs.total_count }}
  new-issues:
    description: "Number of new/reintroduced issues"
    value: ${{ steps.report.outputs.new_count }}
  removed-issues:
    description: "Number of removed issues"
    value: ${{ steps.report.outputs.removed_count }}
  critical-issues:
    description: "Number of critical issues"
    value: ${{ steps.report.outputs.critical_count }}
  high-issues:
    description: "Number of high issues"
    value: ${{ steps.report.outputs.high_count }}
  medium-issues:
    description: "Number of medium issues"
    value: ${{ steps.report.outputs.medium_count }}
  low-issues:
    description: "Number of low issues"
    value: ${{ steps.report.outputs.low_count }}
  scan-failed:
    description: "Whether scan failed due to severity threshold"
    value: ${{ steps.report.outputs.fail_build }}

runs:
  using: "composite"
  steps:
    - name: Login to Fortify SSC
      shell: bash
      run: |
        fcli ssc session login \
          --url ${{ inputs.fortify-ssc-url }} \
          --sc-sast-url ${{ inputs.fortify-sc-sast-url }} \
          -t ${{ inputs.ssc-token }} \
          --insecure \
          -c clienttoken

    - name: Setup SSC Application Version
      if: ${{ inputs.application-version != inputs.base-version }}
      shell: bash
      run: |
        echo "Checking if version ${{ inputs.application }}:${{ inputs.application-version }} exists..."

        # Try to get the version directly - if it exists, command succeeds
        if fcli ssc appversion get "${{ inputs.application }}:${{ inputs.application-version }}" -o json >/dev/null 2>&1; then
          echo "Application version already exists: ${{ inputs.application }}:${{ inputs.application-version }}"
        else
          echo "Creating new application version: ${{ inputs.application }}:${{ inputs.application-version }}"
          fcli ssc appversion create \
            "${{ inputs.application }}:${{ inputs.application-version }}" \
            --copy-from "${{ inputs.application }}:${{ inputs.base-version }}" \
            --auto-required-attrs \
            || echo "::warning::Failed to create version, it may already exist"
        fi

    - name: Create package with source code
      shell: bash
      run: |
        scancentral package -o package.zip

    - name: Start scan session
      shell: bash
      run: |
        fcli sc-sast scan start \
          --publish-to ${{ inputs.application }}:${{ inputs.application-version }} \
          -f package.zip \
          -v ${{ inputs.sast-version }} \
          --store sc_sast_scan

    - name: Waiting for the scan to complete
      shell: bash
      run: |
        fcli sc-sast scan wait-for ::sc_sast_scan::

    - name: Downloading the scan report
      shell: bash
      run: |
        fcli ssc action run github-sast-report \
          --appversion ${{ inputs.application }}:${{ inputs.application-version }}

    - name: Create pull request comment
      if: ${{ github.event_name == 'pull_request' && inputs.enable-report-comment == 'true' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { execSync } = require('child_process');

          function issueDescription(issue) {
              const file = issue.fullFileName.replace(`Src/${{ inputs.application }}/`, '');
              const line = issue.lineNumber == null ? '' : ':' + issue.lineNumber

              return `* ${issue.scanStatus} (${issue.engineCategory}) - ${issue.issueName}:
              [${file}${line}](https://github.com/${owner}/${repo}/blob/${sha}/${file}#L${issue.lineNumber == null ? '' : issue.lineNumber})`
          }

          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const sha = context.sha

          const output = execSync('fcli ssc issue list --av ${{ inputs.application }}:${{ inputs.application-version }} --include visible,removed -o json');
          const parsedOutput = JSON.parse(output).filter(item => !item.suppressed);

          const newIssues = parsedOutput.filter(issue => issue.scanStatus === 'NEW' || issue.scanStatus === 'REINTRODUCED');
          const removedIssues = parsedOutput.filter(issue => issue.scanStatus === 'REMOVED');

          const newIssuesText = newIssues.length > 0
            ? newIssues.map(issueDescription).join("\n")
            : '* No new or re-introduced issues were detected';

          const removedIssuesText = removedIssues.length > 0
            ? removedIssues.map(issueDescription).join("\n")
            : '* No removed issues were detected';

          const prefix = '## Fortify vulnerability summary';
          const body = `${prefix}
          Any issues listed below are based on comparing the latest scan results against the previous scan results for SSC application version **${{ inputs.application }}:${{ inputs.application-version }}**.

          To avoid interference from scans for other PR's or branches, it is recommended to track each PR/branch in a separate SSC application version.

          ### New Issues
          ${newIssuesText}

          ### Removed Issues
          ${removedIssuesText}`;

          await github.rest.issues.createComment({
            issue_number,
            owner,
            repo,
            body
          })

    - name: Generate vulnerability report
      id: report
      shell: bash
      run: |
        report_file=$(mktemp)

        fcli ssc issue list \
          --av ${{ inputs.application }}:${{ inputs.application-version }} \
          --include visible,removed \
          -o json | jq '[.[] | select(.suppressed != true)]' > "$report_file"

        # Calculate statistics
        total_count=$(jq 'length' "$report_file")
        new_count=$(jq '[.[] | select(.scanStatus == "NEW" or .scanStatus == "REINTRODUCED")] | length' "$report_file")
        removed_count=$(jq '[.[] | select(.scanStatus == "REMOVED")] | length' "$report_file")
        critical_count=$(jq '[.[] | select(.friority == "Critical")] | length' "$report_file")
        high_count=$(jq '[.[] | select(.friority == "High")] | length' "$report_file")
        medium_count=$(jq '[.[] | select(.friority == "Medium")] | length' "$report_file")
        low_count=$(jq '[.[] | select(.friority == "Low")] | length' "$report_file")

        # Export outputs
        echo "total_count=$total_count" >> $GITHUB_OUTPUT
        echo "new_count=$new_count" >> $GITHUB_OUTPUT
        echo "removed_count=$removed_count" >> $GITHUB_OUTPUT
        echo "critical_count=$critical_count" >> $GITHUB_OUTPUT
        echo "high_count=$high_count" >> $GITHUB_OUTPUT
        echo "medium_count=$medium_count" >> $GITHUB_OUTPUT
        echo "low_count=$low_count" >> $GITHUB_OUTPUT

        # Generate improved GitHub Step Summary
        {
          echo "## Fortify SAST Scan Results"
          echo ""
          echo "**Application Version:** \`${{ inputs.application }}:${{ inputs.application-version }}\`"
          echo "**Base Version:** \`${{ inputs.base-version }}\`"
          echo ""
          echo "### Summary"
          echo "| Metric | Count |"
          echo "|--------|-------|"
          echo "| Total Issues | $total_count |"
          echo "| New/Reintroduced | $new_count |"
          echo "| Removed | $removed_count |"
          echo ""
          echo "### By Severity"
          echo "| Severity | Count |"
          echo "|----------|-------|"
          echo "| Critical | $critical_count |"
          echo "| High | $high_count |"
          echo "| Medium | $medium_count |"
          echo "| Low | $low_count |"
        } >> $GITHUB_STEP_SUMMARY

        # Add detailed issues table if there are any
        if [ "$total_count" -gt 0 ]; then
          {
            echo ""
            echo "<details>"
            echo "<summary>Issue Details ($total_count issues)</summary>"
            echo ""
            echo "| Priority | Issue Name | File | Line |"
            echo "|----------|------------|------|------|"
          } >> $GITHUB_STEP_SUMMARY

          jq -r '
            sort_by(
              [
                (if .friority == "Critical" then 1
                 elif .friority == "High" then 2
                 elif .friority == "Medium" then 3
                 elif .friority == "Low" then 4
                 else 5 end),
                .impact
              ]
            ) |
            .[] |
            "| \(.friority) | \(.issueName) | \(.fullFileName | sub("^Src/${{ inputs.application }}/";"")) | \(.lineNumber // "-") |"
          ' "$report_file" >> $GITHUB_STEP_SUMMARY

          echo "</details>" >> $GITHUB_STEP_SUMMARY
        fi

        # Check if we should fail the build
        severity_rank() {
          case $1 in
            Critical) echo 4 ;;
            High) echo 3 ;;
            Medium) echo 2 ;;
            Low) echo 1 ;;
            *) echo 0 ;;
          esac
        }
        error_on_severity_rank=$(severity_rank "${{ inputs.exit-with-error-on-severity }}")

        selected_priority_issues_count=$(jq --argjson rank "$error_on_severity_rank" '
          map(select(
            (.friority == "Critical" and 4 >= $rank) or
            (.friority == "High" and 3 >= $rank) or
            (.friority == "Medium" and 2 >= $rank) or
            (.friority == "Low" and 1 >= $rank)
          )) | length
        ' "$report_file")

        rm "$report_file"

        if [ "$selected_priority_issues_count" -gt 0 ]; then
          echo "fail_build=true" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Build will fail due to $selected_priority_issues_count issue(s) at or above ${{ inputs.exit-with-error-on-severity }} severity.**" >> $GITHUB_STEP_SUMMARY
        else
          echo "fail_build=false" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**No blocking issues found at or above ${{ inputs.exit-with-error-on-severity }} severity.**" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Fail if severity threshold exceeded
      if: ${{ steps.report.outputs.fail_build == 'true' }}
      shell: bash
      run: |
        echo "::error::Scan found issues at or above ${{ inputs.exit-with-error-on-severity }} severity"
        exit 1

    - name: Logout from Fortify SSC
      shell: bash
      if: always()
      run: |
        fcli ssc session logout

    - name: Upload scan report as workflow artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: sarif-files
        path: ./gh-fortify-sast.sarif
